name: build

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-18.04
    
    steps:
    - uses: actions/checkout
      with:
        ref: develop
    - name: package
      run: sudo apt-get -y install gfortran mpich libmpich-dev libboost-all-dev libblas-dev liblapack-dev liblapacke-dev libscalapack-mpi-dev
    - name: cmake
      run: mkdir build && cd build && cmake ..
    - name: make
      run: cd build && make
    - name: ctest
      run: cd build && ctest -V
